[package]
name = "nid"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0.56"
serde = "1.0.195"
rand = "0.8.5"

[dev-dependencies]
serde_json = "1.0.114"
pretty_assertions = "1.4.0"
