[package]
name = "nid"
version = "1.0.0"
edition = "2021"
rust-version = "1.61"
description = "Generate and parse Nano IDs"
repository = "https://github.com/ciffelia/nid"
license = "MIT OR Apache-2.0"
keywords = ["nanoid", "unique", "id", "uuid"]
categories = ["data-structures", "parser-implementations"]
exclude = ["/.github", "/.gitignore"]

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", optional = true }
rand = "0.8.5"

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "1.4"
